#**JARINGAN SARAF TIRUAN (NEURAL NETWORK)**
#KLASIFIKASI BUNGA IRIS DENGAN NEURAL NETWORK
#IRIS FLOWER DATASET

In [11]:
#untuk menginstal paket Keras. Keras adalah sebuah library yang populer untuk membangun dan melatih model jaringan saraf tiruan (neural networks) di Python
!pip install keras
import keras
import numpy as np #untuk komputasi numerik di Python, dan memberikan struktur data dan fungsi-fungsi yang kuat untuk bekerja dengan array multidimensi.
from sklearn.datasets import load_iris # Scikit-learn adalah pustaka Python yang populer untuk pembelajaran mesin (machine learning) dan menyediakan berbagai algoritma dan dataset yang siap pakai.
dataset=load_iris() #memuat dataset bunga iris menggunakan fungsi load_iris() dari scikit-learn. Fungsi ini mengembalikan objek dataset yang berisi atribut-atribut dataset, seperti data bunga, label kelas, dan informasi lainnya.
print(dataset) #mencetak objek dataset ke layar. Hal ini digunakan untuk melihat isi dari dataset iris yang telah dimuat.

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6,

In [12]:
# digunakan untuk mengakses dan mencetak informasi yang terkandung dalam dataset iris, termasuk fitur-fitur, label kelas, deskripsi dataset, dan lainnya.
print(type(dataset)) #mencetak tipe objek dari dataset. Outputnya akan memberitahu bahwa objek dataset adalah tipe data sklearn.utils.Bunch, yang merupakan tipe spesifik yang digunakan oleh scikit-learn untuk menyimpan dataset.
print(len(dataset)) #mencetak panjang dataset, yaitu jumlah elemen dalam dataset. Dalam hal ini, panjang dataset akan mencakup beberapa atribut seperti 'data', 'target', 'target_names', dan lainnya.
print(dataset.keys()) #mencetak semua kunci (keys) yang ada dalam dataset. Kunci-kunci tersebut mewakili atribut-atribut yang dapat diakses dalam dataset iris.
print(dataset['data'][0:5]) #mencetak lima baris pertama dari atribut 'data' dalam dataset iris. Atribut 'data' berisi nilai-nilai numerik yang menggambarkan fitur-fitur dari setiap sampel bunga iris.
print(dataset['target'][0:5]) #mencetak lima nilai pertama dari atribut 'target' dalam dataset iris. Atribut 'target' berisi label kelas yang sesuai dengan setiap sampel bunga iris.
print(dataset['target_names'][0:5]) #mencetak lima nama kelas yang terkait dengan dataset iris. Atribut 'target_names' berisi daftar string yang menunjukkan nama kelas yang mungkin dalam dataset iris.
print(dataset['DESCR']) #mencetak deskripsi (description) dari dataset iris. Deskripsi ini berisi informasi rinci tentang dataset, termasuk sumbernya, atribut-atributnya, dan lainnya.
print(dataset['feature_names']) # mencetak nama-nama fitur yang terkait dengan dataset iris. Atribut 'feature_names' berisi daftar string yang menjelaskan setiap fitur numerik dalam dataset iris.
print(dataset['filename'])  #mencetak nama file yang berisi dataset iris.
x=dataset['data'] #menginisialisasi variabel x dengan atribut 'data' dari dataset iris. Variabel x akan berisi fitur-fitur numerik dari dataset.
print(len(x)) #mencetak panjang variabel x, yaitu jumlah sampel dalam dataset iris.
y=dataset['target'] #menginisialisasi variabel y dengan atribut 'target' dari dataset iris. Variabel y akan berisi label kelas yang sesuai dengan setiap sampel.
print(len(y)) # mencetak panjang variabel y, yaitu jumlah label kelas dalam dataset iris.
print(x[0]) #mencetak fitur-fitur numerik dari sampel pertama dalam dataset iris.
print(y[0]) #mencetak label kelas dari sampel pertama dalam dataset iris.


<class 'sklearn.utils._bunch.Bunch'>
8
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ==============

In [13]:

from keras.utils import to_categorical #digunakan untuk mengubah label kelas menjadi representasi one-hot encoding.
Ny=len(np.unique(y)) #menghitung jumlah unik label kelas yang ada dalam y menggunakan fungsi np.unique(y). Nilai ini disimpan dalam variabel Ny.
print(Ny) #mencetak nilai dari Ny, yaitu jumlah unik label kelas dalam dataset iris.
Y=to_categorical(y,num_classes=Ny) #mengubah label kelas y menjadi representasi one-hot encoding dengan menggunakan fungsi to_categorical.
print(Y[0:5]) # mencetak lima baris pertama dari Y, yaitu representasi one-hot encoding dari lima sampel pertama dalam dataset iris.

3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [14]:
#membagi dataset menjadi subset pelatihan dan subset pengujian menggunakan fungsi train_test_split dari scikit-learn
from sklearn.model_selection import train_test_split #digunakan untuk membagi dataset menjadi subset pelatihan dan subset pengujian.
x_train,x_test,y_train,y_test=train_test_split(x,Y,test_size=0.10,shuffle=True) #membagi x dan Y menjadi subset pelatihan dan pengujian.
print(x_train[0:5]) #mencetak lima baris pertama dari subset pelatihan x_train, yaitu fitur-fitur numerik dari sampel-sampel pelatihan.
print(x_test[0:5]) #mencetak lima baris pertama dari subset pengujian x_test, yaitu fitur-fitur numerik dari sampel-sampel pengujian.
print(y_train[0:5]) #mencetak lima baris pertama dari subset pelatihan y_train, yaitu label kelas dalam representasi one-hot encoding dari sampel-sampel pelatihan.
print(y_test[0:5]) #mencetak lima baris pertama dari subset pengujian y_test, yaitu label kelas dalam representasi one-hot encoding dari sampel-sampel pengujian.

[[6.4 2.7 5.3 1.9]
 [4.8 3.4 1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [6.  2.9 4.5 1.5]
 [5.1 3.8 1.5 0.3]]
[[5.  3.3 1.4 0.2]
 [5.6 2.8 4.9 2. ]
 [6.9 3.1 5.1 2.3]
 [7.2 3.  5.8 1.6]
 [4.9 2.4 3.3 1. ]]
[[0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [15]:
#untuk melakukan penskalaan fitur menggunakan StandardScaler dari scikit-learn.
from sklearn.preprocessing import StandardScaler #mengimpor kelas StandardScaler dari modul preprocessing dalam pustaka scikit-learn. Kelas ini digunakan untuk melakukan penskalaan fitur.
import numpy as np #untuk komputasi numerik di Python.
scaler=StandardScaler() #digunakan untuk melakukan penskalaan fitur.
scaler.fit(x_train) #menggunakan objek scaler untuk mempelajari parameter skala dari fitur-fitur dalam x_train
X_train=scaler.transform(x_train) #menggunakan objek scaler untuk melakukan penskalaan fitur dalam x_train. Metode transform digunakan untuk mengubah fitur-fitur dalam x_train berdasarkan parameter skala yang telah dipelajari sebelumnya.
X_test=scaler.transform(x_test) #menggunakan objek scaler untuk melakukan penskalaan fitur dalam x_test. Metode transform digunakan untuk mengubah fitur-fitur dalam x_test berdasarkan parameter skala yang telah dipelajari sebelumnya.
print(np.amax(X_train,axis=0)) #mencetak nilai maksimum dari setiap fitur dalam X_train menggunakan fungsi np.amax dengan axis=0. Outputnya adalah array yang menunjukkan nilai maksimum dari setiap fitur.
print(np.amin(X_train,axis=0)) #mencetak nilai minimum dari setiap fitur dalam X_train menggunakan fungsi np.amin dengan axis=0. Outputnya adalah array yang menunjukkan nilai minimum dari setiap fitur.

[2.57267699 3.02613202 1.80497962 1.74476896]
[-1.84283292 -2.41486007 -1.50121371 -1.48185857]


In [16]:
#untuk membangun dan mengompilasi model jaringan saraf tiruan menggunakan Keras dengan backend TensorFlow.
!pip install tensorflow #TensorFlow adalah platform yang populer untuk pembelajaran mesin dan jaringan saraf tiruan.
import keras # mengimpor pustaka Keras.
from keras.models import Sequential # digunakan untuk membangun model berbasis urutan (sequential model) dalam Keras.
from keras.layers import Dense # digunakan untuk menambahkan lapisan-lapisan (layers) yang terhubung penuh (fully connected layers) ke dalam model.

model = Sequential() # membuat objek model sebagai instance dari kelas Sequential. Objek ini akan digunakan untuk membangun model jaringan saraf tiruan.
model.add(Dense(20, input_dim=X_train.shape[1], activation='relu')) #menambahkan lapisan pertama ke dalam model dengan menggunakan metode add dari objek model. Lapisan ini adalah lapisan Dense dengan 20 unit, dimensi masukan (input dimension) yang sesuai dengan jumlah fitur dalam X_train, dan fungsi aktivasi ReLU.
keras.layers.Dropout(0.2)  #menambahkan lapisan dropout dengan tingkat dropout sebesar 0.2.
model.add(Dense(20, activation='relu')) # menambahkan lapisan kedua ke dalam model. Lapisan ini juga merupakan lapisan Dense dengan 20 unit dan fungsi aktivasi ReLU.
keras.layers.Dropout(0.2) #kembali menambahkan lapisan dropout, namun seperti yang disebutkan sebelumnya, perlu diubah menjadi
model.add(Dense(20, activation='relu')) # menambahkan lapisan ketiga ke dalam model. Lapisan ini juga merupakan lapisan Dense dengan 20 unit dan fungsi aktivasi ReLU.
keras.layers.Dropout(0.2) #menambahkan lapisan dropout, dan seperti sebelumnya, perlu diubah menjadi model.add(keras.layers.Dropout(0.2)) agar lapisan dropout menjadi bagian dari model.
model.add(Dense(3, activation='softmax')) #ini menambahkan lapisan keluaran ke dalam model. Lapisan ini merupakan lapisan Dense dengan
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [17]:
#untuk mencetak ringkasan (summary) dari model jaringan saraf tiruan yang telah dibangun. Ini akan memberikan informasi tentang lapisan-lapisan yang ada dalam model beserta jumlah parameter yang dapat dipelajari pada setiap lapisan.
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 20)                100       
                                                                 
 dense_5 (Dense)             (None, 20)                420       
                                                                 
 dense_6 (Dense)             (None, 20)                420       
                                                                 
 dense_7 (Dense)             (None, 3)                 63        
                                                                 
Total params: 1,003
Trainable params: 1,003
Non-trainable params: 0
_________________________________________________________________


In [21]:
#untuk melatih model jaringan saraf tiruan dengan menggunakan metode fit pada objek model
model.fit(X_train, y_train, epochs=195, batch_size=80, validation_split=0.1)
#Model akan dilatih selama 195 epoch, dengan ukuran batch sebesar 80. Juga, 10% dari data pelatihan akan digunakan sebagai data validasi

Epoch 1/195
2/2 [==============================] - 0s 311ms/step - loss: 0.0434 - accuracy: 0.9835 - val_loss: 0.0887 - val_accuracy: 0.9286
Epoch 2/195
2/2 [==============================] - 0s 143ms/step - loss: 0.0434 - accuracy: 0.9835 - val_loss: 0.0892 - val_accuracy: 0.9286
Epoch 3/195
2/2 [==============================] - 0s 108ms/step - loss: 0.0430 - accuracy: 0.9835 - val_loss: 0.0906 - val_accuracy: 0.9286
Epoch 4/195
2/2 [==============================] - 0s 98ms/step - loss: 0.0425 - accuracy: 0.9835 - val_loss: 0.0928 - val_accuracy: 0.9286
Epoch 5/195
2/2 [==============================] - 0s 35ms/step - loss: 0.0419 - accuracy: 0.9835 - val_loss: 0.0951 - val_accuracy: 0.9286
Epoch 6/195
2/2 [==============================] - 0s 33ms/step - loss: 0.0414 - accuracy: 0.9835 - val_loss: 0.0998 - val_accuracy: 0.9286
Epoch 7/195
2/2 [==============================] - 0s 37ms/step - loss: 0.0410 - accuracy: 0.9917 - val_loss: 0.1060 - val_accuracy: 0.9286
Epoch 8/195
2/2 [

In [22]:
#untuk mengevaluasi model pada data pengujian (testing) dan mencetak akurasi model.
testing=model.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1]+'uracy of Model on testing data ', testing[1]*100))
#dapat melihat dan mencetak akurasi model pada data pengujian setelah model selesai dilatih.


1/1 [==============================] - 0s 42ms/step - loss: 0.0967 - accuracy: 0.9333

accuracyuracy of Model on testing data : 93.33%


In [23]:
#digunakan untuk menghasilkan laporan klasifikasi (classification report) dan matriks kebingungan (confusion matrix) berdasarkan prediksi model pada data pengujian
from sklearn.metrics import classification_report, confusion_matrix #digunakan untuk menghasilkan laporan klasifikasi dan matriks confusion.
predictions = np.argmax(model.predict(X_test), axis=1) # melakukan prediksi pada data pengujian (X_test) menggunakan model yang telah dilatih. Metode predict digunakan untuk menghasilkan probabilitas prediksi kelas. Dengan menggunakan np.argmax dan axis=1, kita mengambil indeks kelas dengan probabilitas tertinggi sebagai prediksi akhir.
Y_test = np.argmax(y_test,axis=1) #mengubah label kelas dari representasi one-hot encoding (y_test) menjadi label kelas asli menggunakan np.argmax. Kita hanya membutuhkan indeks kelas dengan nilai 1 tertinggi.
print(confusion_matrix(Y_test,predictions)) # mencetak matriks kebingungan (confusion matrix) menggunakan fungsi confusion_matrix
print(classification_report(Y_test,predictions))  #mencetak laporan klasifikasi (classification report) menggunakan fungsi classification_report.

1/1 [==============================] - 0s 106ms/step
[[6 0 0]
 [0 3 0]
 [0 1 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       0.75      1.00      0.86         3
           2       1.00      0.83      0.91         6

    accuracy                           0.93        15
   macro avg       0.92      0.94      0.92        15
weighted avg       0.95      0.93      0.94        15



#TERIMA KASIH